add kotik project
alice2205/java pull request #1
Opened 2024-08-05 02:12 UTC by alice2205

2024-08-05 07:40 UTC, Namuman requested changes
хорошо, но надо доделать

2024-08-05 07:40 UTC, Namuman commented on src/main/java/moduleHW1/model/Kotik.java
> +        this.prettiness = 100;
нет метода setKotik

2024-08-05 07:40 UTC, Namuman commented on src/main/java/moduleHW1/model/Kotik.java
> +        kotikCount++;
разберись как работают блоки инициализации, передай с помощь него

2024-08-05 07:40 UTC, Namuman commented on src/main/java/moduleHW1/model/Kotik.java
> +        this.prettiness = 100;
поэтому это лишнее

2024-08-05 07:40 UTC, Namuman commented on src/main/java/moduleHW1/model/Kotik.java
> +    public void eat(int satietyUnits) {
ознакомься с соглашением о стиле кода, должны разделяться одной пустой строкой, но следи, чтобы не было лишних

2024-08-05 07:40 UTC, Namuman commented on src/main/java/moduleHW1/model/Kotik.java
> +            return false;
в методах действий не кормим

2024-08-05 07:40 UTC, Namuman commented on src/main/java/moduleHW1/model/Kotik.java
> +    public void liveAnotherDay() {
метод должен выводить строго 24 строки

2024-08-06 11:25 UTC, alice2205 commented on src/main/java/moduleHW1/model/Kotik.java
> +        this.prettiness = 100;
@Namuman, исправлено.

2024-08-06 11:25 UTC, alice2205 commented on src/main/java/moduleHW1/model/Kotik.java
> +        kotikCount++;
@Namuman, исправлено.

2024-08-06 11:25 UTC, alice2205 commented on src/main/java/moduleHW1/model/Kotik.java
> +    public void eat(int satietyUnits) {
@Namuman, исправлено.

2024-08-06 11:25 UTC, alice2205 commented on src/main/java/moduleHW1/model/Kotik.java
> +            return false;
@Namuman, исправлено.

2024-08-06 11:27 UTC, alice2205 commented on src/main/java/moduleHW1/model/Kotik.java
> +    public void liveAnotherDay() {
@Namuman, и здесь тоже исправлено. Но почему-то флаг outdated не применился.

2024-08-07 06:45 UTC, Namuman approved these changes
исправь одно замечение и можно мержить, принято

2024-08-07 06:45 UTC, Namuman commented on src/main/java/moduleHW1/model/Kotik.java
> +    }
отлично

2024-08-07 06:45 UTC, Namuman commented on src/main/java/moduleHW1/model/Kotik.java
> +    }
название еды нигде не используется

2024-08-10 16:06 UTC, merged